version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: secure_registration_db
    restart: always
    environment:
      POSTGRES_DB: secure_registration
      POSTGRES_USER: regis_user
      POSTGRES_PASSWORD: regis_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U regis_user -d secure_registration"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: pgAdmin untuk GUI management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@regis.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: