apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: gcr.io/model-parsec-465503-p3/backend-secure-onboarding-system:<CHANGE_IMAGE_TAG>
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1"
        envFrom:
        - configMapRef:
            name: backend-config
        # - secretRef:
        #     name: postgres-credentials
        - secretRef:
            name: app-secrets
        env: 
        - name: FIREBASE_CONFIG_PATH
          value: firebase-cred.json
        - name: CORS_ALLOWED_ORIGINS
          value: "http://localhost:3000, http://localhost:5173, http://wondrdesktop.my.id/"
        - name: DB_HOST
          value: postgresql-service.backend
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: url
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
